apiVersion: v1
kind: ConfigMap
metadata:
  name: sqs-sender-config
data:
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://172.21.0.2:31566"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
